[package]
name = "silka-widgets"
description = "Katalog komponen sesuai KOMPONEN.md: API gaya Dart + styling utility ala Tailwind"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
silka-core.workspace = true
silka-theme.workspace = true
silka-paint.workspace = true
silka-text.workspace = true
